In [6]:
#Importing all required libraries
import pandas as pd 
import numpy as np
import seaborn as sns
from tensorflow import keras

In [5]:
#displayin  the data from the file
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [10]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [17]:
#Convert object into label
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species']=le.fit_transform(df['Species'])
df.sample(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
65    66            6.7           3.1            4.4           1.4        1
27    28            5.2           3.5            1.5           0.2        0
37    38            4.9           3.1            1.5           0.1        0
137  138            6.4           3.1            5.5           1.8        2
129  130            7.2           3.0            5.8           1.6        2
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
14    15            5.8           4.0            1.2           0.2        0
2      3            4.7           3.2            1.3           0.2        0
81    82            5.5           2.4            3.7           1.0        1

In [22]:

le.classes_

array([0, 1, 2], dtype=int64)

In [23]:
x = df.drop(columns=['Id','Species'])
y = df['Species']
x.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [24]:
print(y[:5])

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64


In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [27]:
x_train.shape

(105, 4)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
print(x_train[:1])
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_train[:1])
#scale the data into reasonable change

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
94            5.6           2.7            4.2           1.3
[[-0.22332231 -0.89656442  0.34741175  0.20958843]]


In [34]:
#creating binary matrix
y_train = keras.utils.to_categorical(y_train,num_classes=3)
print(y_train[:2])
#['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

[[[[[[[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]


    [[[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]


    [[[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]]



   [[[[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]


    [[[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]


    [[[1. 0. 0.]
      [0. 1. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]

     [[0. 1. 0.]
      [1. 0. 0.]
      [1. 0. 0.]]]]



   [[[[0. 1. 0.]
      [1. 0. 

In [35]:
#building the model 
from keras.models import Sequential
from keras.layers import Dense, Dropout


In [ ]:
model = Sequential()
